### ISSUE TITLE
Bus error: 10

### ISSUE THREAD

**Issue by jaroberts** [cmoncrief/coffeebar#3]
When coffeebar is first started (via cake), it compiles my .coffee files into .js. When I make a change to a file, it compiles again. Then a moment later, it says "Bus error: 10" and drops me to the command line.

![image](https://f.cloud.github.com/assets/1543924/1425805/ef366e2e-404a-11e3-86c0-2141168b71e6.png)

I'm on Mavericks, Node version 0.10.20. This just started happening about a week ago, maybe after an OS X update?

**Comment by cmoncrief** [comment]
It turns out that this was an issue with Sublime Text 3's atomic updates. If you disable that, the behavior will go away.
